spring.application.name=dualshare-backend

spring.datasource.url=jdbc:mysql://localhost:3306/dualshare
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=dhiwbjwtk
cloudinary.api_key=243421854899132
cloudinary.api_secret=MLVWg20OePFUEFwSDYRLH3EaY4E